### ISSUE TITLE
feature/Userinfo Userinfo 컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#11]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Userinfo 컴포넌트를 구현해야 합니다.

### TODO
1. [ ] /userinfo 요청으로 받은 응답을 표시해야 합니다.
2. [ ] 리스트 추가를 누르면 modal 컴포넌트를 표시해야 합니다
3. [ ] 리스트 삭제를 누르면 /removelist 요청을 보내야 합니다.
4. [ ] 리스트 삭제 요청을 보낸 리스트를 지워야 합니다.
5. [ ] /listinfo에서 받은 데이터 중 노래들을 Song컴포넌트에 전달해야 합니다 (Songs)

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
