### ISSUE TITLE
bug/Search infobar와 songlist 사이의 간격 수정, 스크롤 문제 해결

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#113]
### ISSUE
- Group:  `client`
- Type: `bug`
- Detail: infobar와 songlist사이 간격 수정 수정 및 스크롤 문제 해결

### TODO
1. [x] infobar와 songlist사이 간격을 수정해 주세요
2. [x] 화면에서 스크롤이 나타나는 문제를 해결해주세요
3. [x] modal창의 텍스트 색상을 변경해주세요
4. [x] 내 리스트에 저장 문구 수정(저장)
5. [x] 검색창에 검색어가 남아있는 버그 수정
6. [x] Userinfo, Mylist 왼쪽정렬

### Labels
- Estimated time: `E: 3h`
- Group : `client`
