### ISSUE TITLE
bug/Mylist 리스트 추가 시 리스트 이름 길이 제한 추가

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#114]
### ISSUE
- Group:  `client`
- Type: `bug`
- Detail: 리스트 추가 시 리스트 이름 길이 제한 추가

### TODO
1. [x] 리스트 추가 시 리스트 이름 길이 제한 추가
2. [x] 리스트 이름 표시 부분 제거
3. [x] modal css 변경
4. [x] 선택된 노래 표시 글자 크기 축소
5. [x] 선택한 노래 삭제 문구 수정 (삭제)

### Labels
- Estimated time: `E: 3h`
- Group : `client`
