### ISSUE TITLE
feature/AddSong AddSong 컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#14]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: AddSong 컴포넌트를 구현해야 합니다.

### TODO
1. [ ] Song컴포넌트에서 노래를 props로 받아와야 합니다.
2. [ ]  addSongHandler 메소드가 존재해야 합니다.
3. [ ] addSongHandler가 실행 됐을때 /song/add에 노래 삭제 요청을 보내야 합니다.
4. [ ]  요청을 보내면 노래 리스트에서 노래가 삭제되어야 합니다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
