### ISSUE TITLE
feature/Mypage Mypage컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#22]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Mypage에서 데이터를 각각의 컴포넌트에 props로 전달해줘야 합니다.

### TODO
1. [x] Main컴포넌트에서 데이터를 props로 전달받아야 합니다.
2. [x] Userinfo컴포넌트에 유저 정보를 전달해야 합니다. (username, Email, Created_At, List)
3. [x] GET /userinfo로 받은 데이터를 props로 Userinfo 컴포넌트에 전달해야 합니다.

### Userinfo TODO
1. [x] /userinfo 요청으로 받은 응답을 표시해야 합니다.
2. [x] 리스트 추가를 누르면 modal 컴포넌트를 표시해야 합니다
3. [x] 리스트 삭제를 누르면 /removelist 요청을 보내야 합니다.
4. [x] 리스트 삭제 요청을 보낸 리스트를 지워야 합니다.
5. [x] /listinfo에서 받은 데이터 중 노래들을 Song컴포넌트에 전달해야 합니다 (Songs)

### RemoveSong TODO
1. [ ] Song컴포넌트에서 노래를 props로 받아와야 합니다.
2. [ ] removeSongHandler 메소드가 존재해야 합니다.
3. [ ] removeSongHandler가 실행 됐을때 /song/remove에 노래 삭제 요청을 보내야 합니다.
4. [ ] 요청을 보내면 노래 리스트에서 노래가 삭제되어야 합니다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
