### ISSUE TITLE
feature/Login 서버에서 보낸 유저 정보를 저장해야 합니다

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#38]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 로그인, OAuth로그인/회원가입, 회원가입에서 보내는 유저 정보를 저장해야 합니다.

### TODO
1. [ ] 로그인 요청을 보냈을 때 받는 유저 정보를 저장해야 합니다.
2. [ ] OAuth로그인/회원가입 요청을 보냈을 때 받는 유저 정보를 저장해야 합니다.
3. [ ] 회원가입 요청을 보냈을 때 받는 유저 정보를 저장해야 합니다.
4. [ ] 로그인 실패 시 메시지가 출력되어야 합니다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
