### ISSUE TITLE
feature/Modal Modal컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#40]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Modal컴포넌트를 구현해야 합니다.

### TODO
1. [ ] 리스트 추가 버턴을 누르면 Modal컴포넌트가 표시되어야 합니다.
2. [ ] 리스트 이름을 값으로 POST /addlist 요청을 보내야 합니다.
3. [ ] 리스트 요청을 보낸 후 성공 여부를 표시해야 합니다.
4. [ ] 사용자가 창을 닫을 수 있어야 합니다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
