### ISSUE TITLE
feature/Main Main.js컴포넌트를 만들어야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#45]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Main.js컴포넌트를 만들고 Header, Search, Mypage컴포넌트를 포함해야합니다.

### TODO
1. [x] Main.js를 만들고 Search, Mypage컴포넌트 렌더링
2. [x] App.js 라우터를 수정해야 합니다(Search컴포넌트 관련을 Main으로 변경)
3. [x] 로그인 성공 시 /main으로 가도록 변경 
4. [x] Header컴포넌트는 Main컴포넌트에서만 렌더링 되어야 합니다.

### Labels
- Estimated time: `E: 1h`
- Group : `client`
