### ISSUE TITLE
feature/Header Header 컴포넌트를 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#5]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: Header를 구현해야 합니다.

### TODO
1. [ ] Header의 마이페이지 버튼을 눌렀을 때 /mypage 페이지로 이동되어야 합니다.
2. [ ] 로고를 눌렀을 때 /search 페이지로 이동되어야 합니다.
3. [ ] 로그아웃 버튼을 눌렀을때 정상적으로 로그아웃이 되어야 합니다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
