### ISSUE TITLE
feature/Search 노래를 검색할 수 있어야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#6]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 가수, 제목별로 노래를 검색할 수 있어야 합니다.

### TODO
1. [x] 노래를 검색할 경우 스크래핑 서버에 GET / 요청을 보내야 합니다.
2. [x] 서버의 응답에 따라 결과를 보여주어야 합니다.
3. [x] 페이지에 따라 다음 노래들을 표시할 수 있어야 합니다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
