### ISSUE TITLE
feature/Mypage RemoveSong  기능을 구현해야 합니다.

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#69]
### ISSUE
- Group:  `client`
- Type:  `feature`
- Detail: 

### TODO
1. [ ] 노래 리스트에서 선택된 노래가 제거되어야 합니다.
2. [ ] 선택된 노래 개수를 표시할 수 있어야 합니다.
3. [ ] 노래 리스트에 저장된 노래 개수를 표시해야 합니다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
