### ISSUE TITLE
feature/CSS 전체적인 페이지의 CSS를 점검해주세요

### ISSUE THREAD

**Issue by Pangho297** [codestates/SNB-client#80]
### ISSUE
- Group:  `client`
- Type: `feature`
- Detail: 

### TODO
1. [x] Song.css에서 체크박스를 수정해 주세요
2. [x] AddSong에서 드롭박스를 수정해 주세요
3. [ ] Login, Signup CSS를 수정해야 합니다.

### Labels
- Estimated time: `E: 3h`
- Group : `client`
